import { Service, Product, RepairLog } from '@/types';

export const services: Service[] = [
  {
    id: '1',
    category: 'Mobile',
    device: 'iPhone 12/13/14',
    issue: 'Screen Replacement',
    price: 89,
    turnaround: '1h',
  },
  {
    id: '2',
    category: 'Mobile',
    device: 'Samsung S Series',
    issue: 'Screen Replacement',
    price: 110,
    turnaround: '2h',
  },
  {
    id: '3',
    category: 'Mobile',
    device: 'iPhone (All Models)',
    issue: 'Battery Replacement',
    price: 59,
    turnaround: '30m',
  },
  {
    id: '4',
    category: 'Board Repair',
    device: 'MacBook Pro/Air',
    issue: 'Logic Board Repair',
    price: 250,
    turnaround: '24-48h',
    margin: true,
  },
  {
    id: '5',
    category: 'Board Repair',
    device: 'iPhone (All Models)',
    issue: 'Tristar/Charging Port',
    price: 95,
    turnaround: '2h',
    margin: true,
  },
  {
    id: '6',
    category: 'Data Services',
    device: 'Any Device',
    issue: 'Data Recovery',
    price: 150,
    turnaround: 'Variable',
  },
  {
    id: '7',
    category: 'Windows',
    device: 'Laptop/PC',
    issue: 'OS Re-install',
    price: 75,
    turnaround: '2h',
  },
  {
    id: '8',
    category: 'Windows',
    device: 'Gaming PC',
    issue: 'GPU Diagnostics',
    price: 85,
    turnaround: '1h',
  },
];

export const inventory: Product[] = [
  {
    id: 'p1',
    name: 'iPhone 13 Pro',
    category: 'phone',
    specs: { storage: '256GB', screen: 'Good' },
    condition: 'A',
    price: 549,
    imageKey: 'hero',
  },
  {
    id: 'p2',
    name: 'MacBook Air M1',
    category: 'laptop',
    specs: { storage: '512GB', ram: '8GB' },
    condition: 'B',
    price: 699,
    imageKey: 'hero-alt',
  },
  {
    id: 'p3',
    name: 'iPad Pro 12.9"',
    category: 'tablet',
    specs: { storage: '128GB', screen: 'Mint' },
    condition: 'A',
    price: 720,
    imageKey: 'about',
  },
  {
    id: 'p4',
    name: 'Samsung S21',
    category: 'phone',
    specs: { storage: '128GB', screen: 'Cracked' },
    condition: 'C',
    price: 199,
    imageKey: 'service-1',
  },
  {
    id: 'p5',
    name: 'Dell XPS 15',
    category: 'laptop',
    specs: { storage: '1TB', ram: '32GB' },
    condition: 'B',
    price: 899,
    imageKey: 'service-2',
  },
  {
    id: 'p6',
    name: 'iPhone 12',
    category: 'phone',
    specs: { storage: '64GB', screen: 'Good' },
    condition: 'B',
    price: 380,
    imageKey: 'service-3',
  },
  {
    id: 'p7',
    name: 'Surface Pro 7',
    category: 'tablet',
    specs: { storage: '256GB', ram: '8GB' },
    condition: 'A',
    price: 550,
    imageKey: 'gallery-1',
  },
  {
    id: 'p8',
    name: 'ThinkPad X1',
    category: 'laptop',
    specs: { storage: '512GB', ram: '16GB' },
    condition: 'A',
    price: 750,
    imageKey: 'gallery-2',
  },
];

export const repairLogs: RepairLog[] = [
  { device: 'iPhone 11', status: 'FIXED', time: '12ms' },
  { device: 'MacBook Air M1', status: 'FIXED', time: '1h 20m' },
  { device: 'Samsung S20', status: 'PROCESSING', time: 'In Progress' },
  { device: 'iPad Gen 8', status: 'FIXED', time: '45m' },
  { device: 'PS5 Disc Drive', status: 'FIXED', time: '2h 10m' },
  { device: 'iPhone 13 Pro', status: 'PROCESSING', time: 'In Progress' },
  { device: 'Dell Latitude', status: 'FIXED', time: '3h 05m' },
];